groups:
- default
- plots
- spleef
- spleeflobby
- mamby
- elytra
- hallofjustice
- techcombatknockbackgame
- anarchy
- chess
- checkers
- marathon
- splegg
- elytra
- formuladrift
- turfwars
- crossfire
- boatrace
- vampirez
- escaperoom
- pvpworldsruins
- pvpworldsundergroundarmory
- pvpworldsforest
- hilariousrace
- garbageworld
- deathmachine
- deathrun
- flyingbattlearena
- office
- rollercoaster
- underworld
- extremesumo
- skywars
- lasertag
- turbotowers
- soccer
- kingoftheladder
worlds:
  survival: default
  survival_nether: default
  survival_the_end: default
  greenfield: default
  speedforce: default
  metropolis: default
  gotham: default
  fortressofsolitude: default
  destructiblecity: default
  superherocity: default
  waynemanor: default
  infinitycity: default
  hallofjustice: hallofjustice
  techcombatknockbackgame: techcombatknockbackgame
  anarchy: anarchy
  anarchy_nether: anarchy
  anarchy_the_end: anarchy
  chess: chess
  checkers: checkers
  marathon: marathon
  spleef: spleef
  spleeflobby: spleeflobby
  plots: plots
  skeeter: mamby
  skeeter_nether: mamby
  skeeter_the_end: mamby
  elytraeasy: elytra
  elytramedium: elytra
  elytrahard: elytra
  elytrapvp: elytra
  elytrapole: elytra
  formuladrift: formuladrift
  turfwars: turfwars
  crossfire: crossfire
  boatrace: boatrace
  pvpworldsforest: pvpworldsforest
  pvpworldsundergroundarmory: pvpworldsundergroundarmory
  pvpworldsruins: pvpworldsruins
  escaperoom: escaperoom
  hilariousrace: hilariousrace
  garbageworld: garbageworld
  splegg: splegg
  deathmachine: deathmachine
  deathrun: deathrun
  flyingbattlearena: flyingbattlearena
  office: office
  utopia: office
  rollercoaster: rollercoaster
  underworld: underworld
  extremesumo: extremesumo
  skywars: skywars
  lasertag: lasertag
  turbotowers: turbotowers
  soccer: soccer
  kingoftheladder: kingoftheladder
  vampirez: vampirez
respect-gamemode: false
