Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
  - "&4&l--------------------\n&cAttention Players: &4The IP Address of the server is going to change! Make sure you connect using &a&lmynecraft.servegame.com &4or &a&lplay.serveminecraft.net &4&lnot 66.228.50.54\n&4The server will go offline up to 2 days during IP change. \n&4&l--------------------"
        # - "&7This server supports all canon (&lnot &7fanfic) characters"
        # - "&7Commands you should know: &a/recipe&7, &a/co i&7, &a/home <plr>:&7, &a/powers"
        # - "&7Need to contact the owner? Send an email to &amalonnnnn@gmail.com"
        # - "&7We now accept donations: &ahttps://goo.gl/BmxAqv"
        # - "&7You can now go to &a/warp rules &7to see the new server rules!"
        # - "&7Want free &lOP &7heroes? Then apply to be staff! &e&lD&a&lN&4&lA &f&lEngineers&7, &e&lD&a&lN&4&lA &a&lC&b&lo&c&ls&d&lm&e&le&f&lt&5&li&6&lc&2&ls&7, and &a&lVR &b&lConstructor&7! Drop off your application at &a/warp staffapps"
