Broadcast-Inverval: 1m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
  - "&b ----------------------------------------------------\n
&e&k!!!&a Big server changes! Please fill out the questionaire!\n
&e&k!!!&c https://goo.gl/forms/y69XaDkji0vIwpSi2\n
&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lThere is now a minecart at the bottom of\n
#&c&l/warp city &a&lthat takes you to the lab.\n
#The lab's button has been moved &c&lcloser &a&lso that\n
#a single person can now switch heroes by themself\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&7This server supports &aall canon &7(&4&lnot &4fanfic&7) &7characters&7\n
#It is &lFEATS ONLY&7, meaning none of that wiki bullshit.\n
#Only shit that's &lACTUALLY&7 been shown in a comic, game,\n
#TV, Movie, or other fuckin' authorized merch.\n
#&lONLY PICS OR VIDS COUNT AS PROOF, YA CUNTS!\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&7Handy fuckin' commands: &a/recipe&7, &a/co i&7, &a/home <plr>:&7,\n
#&a/powers&7, &a/mortal&7, &a/disguiseviewself&7, &a/who&7,\n
#&a/listheroes <pagenum>&7, &a/id <classname>&7\n
#&b----------------------------------------------------"
# - "&b ----------------------------------------------------\n
#Summon &4&lThe Alpha &busing the portals at &c/warp city&b\n
#and at the lab. It's a guaranteed way to get ahold of the\n
#owner\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&7We now beg for irl money: &ahttps://goo.gl/BmxAqv&7\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&dIs the server fucked up?\n
#&dAre we missing the most badass character of all time?\n
#&4&lThen fucking click here\n
#&ahttps://github.com/malonnnn/ServerConfig/issues\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a/warp rollercoaster&6 - this place sucks if you hate rollercoasters\n
#&a/warp infiniteparkour&6 - the shortest parkour ever\n
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lThe server requires rule a new rule master.\n
#&bIf you feel you would make a worthy rule master, please\n
#visit &6/warp plots &band build a set of rules that the\n
#server can abide by. On &aFeb 24th at 1pm CST &ba \n
#vote will begin\n on who made the best rules.\n
#Winner will be awarded offical rule master and\n
#be in charge of the server police force.\n
#You can read submissions of rules by using\n
#the command &6/warp rules<num> &b. For example,\n
#&6/warp rules3
#&b----------------------------------------------------"
#  - "&b ----------------------------------------------------\n
#&a&lTIME TO START VOTING ON &c&lBEST SERVER RULES\n
#&a&lTHE WINNER WILL BE THE NEW &c&lPOLICE CHIEF &a&lAND\n
#A NEW &c&lRULE MASTER&a&l!!!\n
#&c&lhttp://www.strawpoll.me/12410065\n
#&b----------------------------------------------------"
