Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
    - "&7This server supports all canon (&lnot &7fanfic) characters"
    - "&7Commands you should know: &a/recipe&7, &a/co i&7, &a/home <plr>:&7, &a/powers"
    - "&7Need to contact the owner? Send an email to &9malonnnnn@gmail.com"
    - "&7We now accept donations: &ahttps://goo.gl/BmxAqv"
    - "&7You can now go to &a/warp rules &7to see the new server rules!"
