Broadcast-Inverval: 5m
Auto-Broadcast: true
Random-Order: false
Ignore-Delay: 1h
Prefixes:
  Console: '&5[CONSOLE]&f '
  Default: ''
  '@W': '&4[WARNING]&f '
  '@T': '&5[TIP]&f '
Messages:
  - "&b ----------------------------------------------------\n
&7This server supports &aall canon &7(&4&lnot &4fanfic&7) &7characters&7\n
It is &lFEATS ONLY&7, meaning only powers and abilities that\n
have &lACTUALLY&7 been shown in a comic, game, TV, Movie, etc.\n
Wikipedia and random websites &lDO NOT &7count unless it's\n
an &lOFFICIAL &7website.\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7Commands you should know: &a/recipe&7, &a/co i&7, &a/home <plr>:&7,\n
&a/powers&7, &a/mortal&7, &a/disguiseviewself&7, &a/who&7,\n
&a/listheroes <pagenum>&7, &a/id <classname>&7\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7New staff position available! &4Redstone Master&7\n
&6You will be tasked with helping add redstone to\n
and commandblock codes to minigame builds\n
You will not get direct access to command blocks as that's\n
not possible.\n
In exchage you get free OP heroes and no chat timer.\n
&lPOSITION NOT FILLED\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&7We now accept donations: &ahttps://goo.gl/BmxAqv&7\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&6Need to report a bug? Need to suggest an improvement? Need to suggest a whole new hero? Do it here!\n
&ahttps://github.com/malonnnn/ServerConfig/issues\n
&b----------------------------------------------------"
  - "&b ----------------------------------------------------\n
&6Available Staff Positions\n
&e&lD&a&lN&4&lA &f&lEngineers&7 (makes heroes)\n
&e&lD&a&lN&4&lA &a&lC&b&lo&c&ls&d&lm&e&le&f&lt&5&li&6&lc&2&ls&7 (makes skins)\n
&a&lVR &b&lConstructor&7 (builds stuff)\n
&aInformation Manager&7 (keeps info station up to date)\n
&4Redstone Master&7 (creates redstone/command block commands)\n
&b----------------------------------------------------"
