# 
# Whether or not resourcepack file hashes should be generated on startup:
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  survival:
    url: http://mynecraft.servegame.com/pp.zip
    hash: 1e4e28db225daabdbad18b27d31db32bdd436fa7
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.survival
empty: survival
server:
  pack: survival
worlds:
  survival112:
    pack: survival
