# 
# Whether or not resourcepack file hashes should be generated on startup:
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  broville:
    url: http://mynecraft.servegame.com/broville.zip?raw=true
    hash: 96985bb0d3f89a1035706a067b8a7761b408f6d1
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.broville
  greenfield:
    url: http://mynecraft.servegame.com/greenfield.zip?raw=true
    hash: 77d76fdc6ad218251895f37c6dda5cdcd5ec9894
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.greenfields
  gotham:
    url: http://mynecraft.servegame.com/gotham.zip?raw=true
    hash: 846185eaf270c3ca009e7e7e5bf4e0a58fb837e0
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.gotham
  emptypack:
    url: https://github.com/Phoenix616/BungeeResourcepacks/blob/master/Empty.zip?raw=true
    hash: c05faed4680570a6159823e13fbae2ae830166ab
    format: 0
    restricted: false
    permission: worldresourcepacks.pack.emptypack
empty: emptypack
server:
  pack: emptypack
  send-delay: 200
worlds:
  gotham:
    pack: gotham
  greenfield:
    pack: greenfield
  broville:
    pack: broville
